INPUT_VALIDATIONS = {
    "audio_file": {"type": str, "required": True},
    "model": {
        "type": str,
        "required": False,
        "default": "faster-whisper-large-v3-russian",
    },
    "language": {"type": str, "required": False, "default": None},
    "device": {"type": str, "required": False, "default": "cuda"},
    "device_index": {"type": int, "required": False, "default": None},
    "compute_type": {"type": str, "required": False, "default": "float16"},
    "language_detection_min_prob": {"type": float, "required": False, "default": 0},
    "language_detection_max_tries": {"type": int, "required": False, "default": 5},
    "initial_prompt": {"type": str, "required": False, "default": None},
    "batch_size": {"type": int, "required": False, "default": 64},
    "beam_size": {"type": int, "required": False, "default": None},
    "temperature": {"type": float, "required": False, "default": 0},
    "temperature_increment_on_fallback": {
        "type": float,
        "required": False,
        "default": None,
    },
    "vad_onset": {"type": float, "required": False, "default": 0.500},
    "vad_offset": {"type": float, "required": False, "default": 0.363},
    "align_output": {"type": bool, "required": False, "default": False},
    "output_format": {"type": str, "required": False, "default": "json"},
    "diarization": {"type": bool, "required": False, "default": False},
    # alias for compatibility with other workers
    "diarize": {"type": bool, "required": False, "default": None},
    "huggingface_access_token": {"type": str, "required": False, "default": None},
    "min_speakers": {"type": int, "required": False, "default": None},
    "max_speakers": {"type": int, "required": False, "default": None},
    "length_penalty": {"type": float, "required": False, "default": None},
    "debug": {"type": bool, "required": False, "default": False},
    "speaker_verification": {"type": bool, "required": False, "default": False},
    "speaker_samples": {"type": list, "required": False, "default": []},
}
