INPUT_VALIDATIONS = {
    "audio_file": {"type": str, "required": True},
    "model": {
        "type": str,
        "required": False,
        "default": "faster-whisper-large-v3-russian",
    },
    "language": {"type": str, "required": False, "default": None},
    "compute_type": {"type": str, "required": False, "default": "float16"},
    "language_detection_min_prob": {"type": float, "required": False, "default": 0},
    "language_detection_max_tries": {"type": int, "required": False, "default": 5},
    "batch_size": {"type": int, "required": False, "default": 64},
    "beam_size": {"type": int, "required": False, "default": None},
    "temperature": {"type": float, "required": False, "default": 0},
    "temperature_increment_on_fallback": {
        "type": float,
        "required": False,
        "default": None,
    },
    "vad_onset": {"type": float, "required": False, "default": 0.30},
    "vad_offset": {"type": float, "required": False, "default": 0.250},
    "min_duration_on": {"type": float, "required": False, "default": 0.08},
    "min_duration_off": {"type": float, "required": False, "default": 0.08},
    "pad_onset": {"type": float, "required": False, "default": 0.0},
    "pad_offset": {"type": float, "required": False, "default": 0.0},
    "align_output": {"type": bool, "required": False, "default": False},
    "output_format": {"type": str, "required": False, "default": "json"},
    "diarization": {"type": bool, "required": False, "default": False},
    "diarize": {"type": bool, "required": False, "default": None},
    "huggingface_access_token": {"type": str, "required": False, "default": None},
    "min_speakers": {"type": int, "required": False, "default": None},
    "max_speakers": {"type": int, "required": False, "default": None},
    "length_penalty": {"type": float, "required": False, "default": None},
    "no_speech_threshold": {"type": float, "required": False, "default": 0.60},
    "log_prob_threshold": {"type": float, "required": False, "default": -1.0},
    "compression_ratio_threshold": {"type": float, "required": False, "default": 2.4},
    "debug": {"type": bool, "required": False, "default": False},
}
